import type { Trainer, DietPlanCard, Testimonial, FAQItem, NavLink } from '@/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '/' },
  { label: 'Trainers', href: '/#trainers' },
  { label: 'Plans', href: '/#plans' },
  { label: 'Results', href: '/#results' },
  { label: 'Contact', href: '/#contact' },
]

export const TRAINERS: Trainer[] = [
  {
    id: 'vishal',
    name: 'Vishal',
    slug: 'vishal',
    title: 'Head Coach',
    specialization: 'Fat Loss & Strength Transformation',
    experience: 8,
    clientsHelped: 500,
    certifications: ['Certified Fitness Coach', 'Online Transformation Specialist', 'Precision Nutrition Level 1'],
    achievements: [
      'Helped 500+ clients achieve their goals',
      'Certified Fitness Coach with 8 years experience',
      'Online Transformation Specialist',
      'Average client loses 8–12 kg in 12 weeks',
    ],
    bio: 'Vishal has spent 8 years perfecting the science of body recomposition. His data-driven approach to fat loss combined with strength programming has transformed hundreds of physiques across India.',
    avatarUrl: '/images/trainers/vishal.jpg',
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_VISHAL ?? '+919999999999',
  },
  {
    id: 'sharon',
    name: 'Sharon',
    slug: 'sharon',
    title: 'Nutrition & Muscle Coach',
    specialization: 'Muscle Building & Nutrition',
    experience: 6,
    clientsHelped: 300,
    certifications: ['Sports Nutrition Specialist', 'Certified Personal Trainer', 'Yoga Alliance RYT-200'],
    achievements: [
      'Sports Nutrition Specialist',
      'Certified Personal Trainer',
      'Helped 300+ clients build lean muscle',
      "Specialist in women's fitness & body composition",
    ],
    bio: 'Sharon blends precision nutrition with evidence-based training to build strong, athletic bodies. Her approach focuses on sustainable muscle building without sacrificing health or lifestyle.',
    avatarUrl: '/images/trainers/sharon.jpg',
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_SHARON ?? '+919999999998',
  },
]

export const DIET_PLANS: DietPlanCard[] = [
  {
    id: 'fat-loss-starter',
    title: 'Fat Loss Starter',
    description: 'A structured 4-week plan designed to ignite your metabolism and shed initial body fat with sustainable habits.',
    category: 'Fat Loss',
    price: 999,
    originalPrice: 1499,
    trainerName: 'Vishal',
    trainerSlug: 'vishal',
    durationWeeks: 4,
    mealsPerDay: 4,
    caloriesRange: '1400–1700 kcal',
    features: ['Full meal plan with recipes', 'Macro breakdowns', 'Grocery shopping list', 'Email support'],
    isPopular: false,
  },
  {
    id: 'fat-loss-advanced',
    title: 'Fat Loss Pro',
    description: '12-week progressive cutting plan for those serious about sustainable fat loss and visible abs.',
    category: 'Fat Loss',
    price: 2499,
    originalPrice: 3499,
    trainerName: 'Vishal',
    trainerSlug: 'vishal',
    durationWeeks: 12,
    mealsPerDay: 5,
    caloriesRange: '1600–2000 kcal',
    features: ['Progressive caloric cycling', 'Refeed days included', 'Weekly check-in templates', '24/7 WhatsApp support', 'Supplement guide'],
    isPopular: true,
  },
  {
    id: 'muscle-gain-beginner',
    title: 'Muscle Builder — Beginner',
    description: 'The perfect starting point for muscle building. Learn to eat for growth with a structured 6-week plan.',
    category: 'Muscle Gain',
    price: 1299,
    originalPrice: 1799,
    trainerName: 'Sharon',
    trainerSlug: 'sharon',
    durationWeeks: 6,
    mealsPerDay: 5,
    caloriesRange: '2200–2600 kcal',
    features: ['High-protein meal templates', 'Pre/post workout nutrition', 'Calorie surplus calculator', 'Supplement guide'],
    isPopular: false,
  },
  {
    id: 'muscle-gain-advanced',
    title: 'Lean Bulk Protocol',
    description: '16-week clean bulk plan to pack on maximum muscle with minimal fat gain. Periodized nutrition strategy.',
    category: 'Muscle Gain',
    price: 3299,
    originalPrice: 4499,
    trainerName: 'Sharon',
    trainerSlug: 'sharon',
    durationWeeks: 16,
    mealsPerDay: 6,
    caloriesRange: '2800–3400 kcal',
    features: ['Caloric periodization', 'Deload week nutrition', 'Blood work interpretation guide', '1-on-1 monthly call', 'Custom macro targets'],
    isPopular: true,
  },
  {
    id: 'vegetarian-fat-loss',
    title: 'Veg Fat Loss Plan',
    description: 'Prove that plant-based eating can power serious fat loss. 8 weeks of high-protein vegetarian meals.',
    category: 'Vegetarian',
    price: 1499,
    originalPrice: 1999,
    trainerName: 'Sharon',
    trainerSlug: 'sharon',
    durationWeeks: 8,
    mealsPerDay: 4,
    caloriesRange: '1500–1800 kcal',
    features: ['100% vegetarian meals', 'High-protein recipes', 'Indian cuisine friendly', 'Snack ideas included'],
    isPopular: false,
  },
  {
    id: 'keto-plan',
    title: 'Keto Reset',
    description: 'Kickstart fat adaptation with a guided 6-week ketogenic diet plan — optimized for Indian tastes.',
    category: 'Keto',
    price: 1799,
    originalPrice: 2499,
    trainerName: 'Vishal',
    trainerSlug: 'vishal',
    durationWeeks: 6,
    mealsPerDay: 3,
    caloriesRange: '1600–1900 kcal',
    features: ['Keto induction protocol', 'Indian keto recipes', 'Electrolyte guide', 'Carb cycling introduction'],
    isPopular: false,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Arjun Sharma',
    location: 'Mumbai',
    before: '94 kg',
    after: '76 kg',
    weightLost: '18 kg',
    duration: '14 weeks',
    quote: "Vishal's Fat Loss Pro plan is the only thing that has ever worked for me. The structure, the support, the results — everything exceeded my expectations. I feel like a completely different person.",
    trainerName: 'Vishal',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Nair',
    location: 'Bangalore',
    before: '68 kg',
    after: '58 kg',
    weightLost: '10 kg',
    duration: '10 weeks',
    quote: "Sharon's vegetarian plan showed me that plant-based eating can be absolutely delicious and effective. I never felt deprived, and the results speak for themselves.",
    trainerName: 'Sharon',
    rating: 5,
  },
  {
    id: '3',
    name: 'Rahul Verma',
    location: 'Delhi',
    before: '72 kg',
    after: '80 kg',
    weightLost: null,
    duration: '16 weeks',
    quote: "The Lean Bulk Protocol is the most comprehensive nutrition guide I've encountered. Sharon's attention to detail and the 1-on-1 call each month made all the difference.",
    trainerName: 'Sharon',
    rating: 5,
  },
  {
    id: '4',
    name: 'Kavya Reddy',
    location: 'Hyderabad',
    before: '80 kg',
    after: '65 kg',
    weightLost: '15 kg',
    duration: '12 weeks',
    quote: "I tried everything before Melior. This was the first time I had a real plan tailored to my lifestyle. The WhatsApp support from Vishal kept me accountable every single day.",
    trainerName: 'Vishal',
    rating: 5,
  },
]

export const FAQS: FAQItem[] = [
  {
    question: 'How is a personalized diet plan different from a generic one?',
    answer: 'Our plans are built around your specific goals, body metrics, food preferences, and lifestyle. We factor in your Indian food preferences, budget, cooking time, and target macros — unlike one-size-fits-all templates.',
  },
  {
    question: 'Do I need to go to a gym to follow these plans?',
    answer: 'Diet plans are nutrition-focused and work with or without gym training. However, if you opt for personal coaching, we pair your nutrition with a training plan optimized for your equipment access.',
  },
  {
    question: 'How do I receive my diet plan after purchase?',
    answer: 'Immediately after payment, you get access to your plan in the dashboard. You can view, download, and track it digitally. The plan is also emailed to you as a PDF within 24 hours.',
  },
  {
    question: 'Is there a refund policy?',
    answer: 'We offer a 7-day satisfaction guarantee. If you follow the plan for 7 days and are not satisfied with the quality, we will issue a full refund — no questions asked.',
  },
  {
    question: 'What is the difference between a diet plan and personal coaching?',
    answer: 'A diet plan is a fixed document you follow at your own pace. Personal coaching is a live relationship — weekly check-ins, plan adjustments, WhatsApp access, and accountability with your chosen trainer.',
  },
  {
    question: 'Can I switch trainers after starting?',
    answer: 'Yes. If you feel you are a better fit with the other trainer, just message us and we will facilitate the transition with no extra cost.',
  },
]

export const PLAN_CATEGORIES = [
  'All',
  'Fat Loss',
  'Muscle Gain',
  'Vegetarian',
  'Keto',
  'Beginner',
  'Advanced',
] as const

export const STATS = [
  { label: 'Clients Transformed', value: '800+' },
  { label: 'Diet Plans Sold', value: '2,400+' },
  { label: 'Avg Weight Lost', value: '11 kg' },
  { label: 'Satisfaction Rate', value: '98%' },
]
